name: Tweet

on:
  schedule:
    - cron: "5 7 * * *"
    - cron: "5 9 * * *"
    - cron: "5 11 * * *"
    - cron: "5 13 * * *"
    - cron: "5 15 * * *"
    - cron: "5 17 * * *"
    - cron: "5 19 * * *"
    - cron: "5 21 * * *"
  workflow_dispatch:
    inputs:
      script_args:
        description: Script options
        required: true

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Python packages 💾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install packages ⚙
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Use HEREDOC for run to escape possible single and double quotes in the message.
      - name: Post tweet to Twitter 🐦
        env:
          CONSUMER_KEY:    ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY:      ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET:   ${{ secrets.ACCESS_SECRET }}
          SCRIPT_ARGS: ${{ contains(github.event.schedule, '7') && '-i 0' || contains(github.event.schedule, '9') && '-i 0 -r' || contains(github.event.schedule, '11') && '-i 1' || contains(github.event.schedule, '13') && '-i 1 -r' || contains(github.event.schedule, '15') && '-i 2' || contains(github.event.schedule, '17') && '-i 2 -r' || contains(github.event.schedule, '19') && '-i 3' || contains(github.event.schedule, '21') && '-i 3 -r' || github.event.inputs.script_args }}
        run: |
          python tweet.py $SCRIPT_ARGS
